export const actions = {
  RETRIEVE_ERROR: 'RETRIEVE_ERROR',
  ADD_SEARCH: 'ADD_SEARCH',
  ADD_FAVORITE: 'ADD_FAVORITE',
  CLEAR_FAVORITES: 'CLEAR_FAVORITES',
  CLEAR_RECENT: 'CLEAR_RECENT',
  MOVIE_LENGTH: 'MOVIE_LENGTH',
  SERIES_LENGTH: 'SERIES_LENGTH',
  EPISODE_LENGTH: 'EPISODE_LENGTH',
  ADD_TO_LIST: 'ADD_TO_LIST',
  NEW_SEARCH: 'NEW_SEARCH',
  HAS_RESULTS: 'HAS_RESULTS',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  CURRENT_SEARCH: 'CURRENT_SEARCH'
}

export const configs = {
  apiUrl: 'https://www.omdbapi.com',
  notFound: 'Result not found!'
}
